### PR TITLE
Divide OnUpdateListener

### PR DESCRIPTION
**Pull request by danielpassos**
I've divided the `OnUpdateListener` in two new classes. `OnDeleteCompleteListener` and `OnLoadCompleteListener`.

I think the protected field is enough to use that

**In My Activity/Fragment**
```Java
public class MyActivity extends AppCompatActivity implements FlexibleAdapter.OnDeleteCompleteListener  {

    @Override
    public void onDeleteConfirmed() {
        for (MyDomainClass item : mAdapter.getDeletedItems()) {
            // Delete from Database
        }
    }

}
```
**In My Adapter**
```Java
public class MyRecyclerViewAdapter
        extends FlexibleAdapter<MyViewHolder, MyDomainClass> {

    public RecyclerViewAdapter(FlexibleAdapter.OnDeleteCompleteListener onDeleteCompleteListener) {
            super.onDeleteCompleteListener = onDeleteCompleteListener;
    }

}
```

Another option is force pass it in construction but I don't like that style. Wdyt?

### CODE REVIEW

**Comment by danielpassos** [comment]
@davideas I've reformat code in all classes I've changed using tab instead space. Could you check that?

**Comment by davideas** [comment]
@danielpassos, ah ok I was writing if you could apply the change, you did it already, I have to go now, I will check later.

**Comment by davideas** [comment]
@danielpassos, do you know if I can pull only a single commit or I am obliged to pull everything?

**Comment by danielpassos** [comment]
@davideas You can do whatever you want it's your project. You can

1. Ask me to [squashing](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html) it in one commit
1. You can squashing it yourself
1. You can merge it with --no-ff (it will create a new commit)

But in 1. You can squashing it general if you don't have, duplicated commits, or something wrong, we leave it as it, to keep the historical of what was done.

Anyway I have no problem about squashing it in one commit if you want

**Comment by davideas** [comment]
hmm.. not expert of these Git functionalities. I will pull everything in Dev and then start to adapt/remove some code.

**Comment by danielpassos** [comment]
@davideas Go ahead. Ping me if you need some help or something from my side.

**Comment by danielpassos** [comment]
Hey @davideas Do you want a close that and send a new one for `dev` branch with one only commit?

**Comment by davideas** [comment]
ok let's do it.

**Comment by danielpassos** [comment]
Closing that in favor a new one to a `dev` branch

**Pull request closed without merging**
